### ISSUE TITLE
Merge different lines for same run, luminometer, calibrations

### ISSUE THREAD

**Issue by capalmer85** [CMS-LUMI-POG/NormtagsV0Deprecated#16]

**Comment by capalmer85** [comment]
In makeCompositeNTs.py.  For example, one could have:

["pccLUM15001",{"274251":[[19, 78], [82, 93], [100, 102], [115, 117], [121, 123], [136, 138], [203, 205]]}],
["pccLUM15001",{"274251":[[1, 18], [79, 81], [94, 99], [103, 114], [118, 120], [124, 135], [139, 202], [206, 547]]}],

if LSs are added at different times or from separate normtag json files.

**Comment by plujan** [comment]
closing old issues (I believe the current version of makeCompositeNTs.py fixes this also)
