### ISSUE TITLE
Automate bad LS finding per luminometer

### ISSUE THREAD

**Issue by capalmer85** [CMS-LUMI-POG/NormtagsV0Deprecated#8]
1) in makePerLumiNTs.py find the histograms which are plotted.
2) implement an algorithm that requires smoothness in luminosity and in ratio.
  i) first step is to look for "steps" in lumi
  ii) obvious exception is during optimization scans
3) program should make/print bad LS suggestions for all three luminometer
4) assume that all suggested bad LSs are removed and write the normtag_luminometer.json
  i) we will go back and sort out how to make changes to suggested bad list later

**Comment by DavidSticklandCMS** [comment]
0) Actually the first thing may be to correctly identify the missing LS. In the problem reported this week [(273447, 32), (273447, 37), (273447, 41)] these LS are not in the PLT at all, but the  makePerLumiNTs.py happily said the whole run was present. In addition the candidate normtag lines should not point to the online lumi but to the current offline lumi (e.g. hfoc16v1) and likewise the plotting should specify those norm tags and any comparisons between luminometers should use those norm tags..
4) is maybe tricky. You could end up removing all candidates for some LS.

5) sometimes (at least now) a step in (e.g.) PLT is clearly a sign of  problem, but moving to one of the other luminometers may be a bigger change than just a accepting the step

**Comment by capalmer85** [comment]
On Fri, May 27, 2016 at 3:16 PM, DavidSticklandCMS <notifications@github.com

> wrote:
> 
> 0) Actually the first thing may be to correctly identify the missing LS.
> In the problem reported this week [(273447, 32), (273447, 37), (273447,
> 41)] these LS are not in the PLT at all, but the makePerLumiNTs.py happily
> said the whole run was present. In addition the candidate normtag lines
> should not point to the online lumi but to the current offline lumi (e.g.
> hfoc16v1) and likewise the plotting should specify those norm tags and any
> comparisons between luminometers should use those norm tags..
> 
> This will actually be caught in 2).  If there is no lumi in a bin, then a
> good algorithm will see 0 as a "step".  Even if you want to view this as a
> separate step... Krishna needs to have access to the histograms first so he
> can check for empty bins and that is step 1).

Currently the algo is to look at the plot and search for mistakes.  I
imagine that is why this was missing.  (Another reason could be that LSs
are averaged over in the histogram.)  In any event, we should validate the
eventual product on these runs to see that it removes these LSs.

I may make an additional issue for validation of the tool and put these LSs
there as a reminder.

> 4) is maybe tricky. You could end up removing all candidates for some LS.
> 
> Read i) and recall that we are really still in development.  We should have
> an option of accepting all the suggestions.  After that we should put in
> additional workflow for the user to decide if things look correct or ignore
> some vetoes.

This is the very next thing to do after the simple stuff is developed.

**Comment by thapakrish** [comment]
@DavidSticklandCMS 

> In the problem reported this week [(273447, 32), (273447, 37), (273447, 41)] these LS are not in the PLT at all, but the makePerLumiNTs.py happily said the whole run was present.

This is unfortunate--I use the same method that bestlumi.py uses to make those suggestions. Same suggestion can be reproduced by doing

'brilcalc lumi -f 4926 -o output.csv --byls -b "STABLE BEAMS" --type pltzero'
'python /afs/cern.ch/user/c/cmsbril/public/bestlumi.py output.csv'
'    ["pltzerov1",{"273447":[[1,427]]}]'

Given just one luminometer, bestlumi.py gives this weird result for 273447. I'll take a look at this.

@capalmer85 

>  in makePerLumiNTs.py find the histograms which are plotted

I'm not familiar about how to keep matplotlib objects around---maybe import lumiValidate from makePerLumiNTs.py and use lumiValidate.get_data method to grab data, then call lumiValidate.plot_methods for plots.

**Comment by thapakrish** [comment]
@capalmer85 lumiValidate.get_data and other methods have very specific requirement on argument. Calling those methods from makeBPerLumiNTs.py is going to be a challenge. One way around is to pipe out the data used for plots to a file and read it again.
'print merged, got_cols, fill ' 
at the end of get_data method should do the trick.

**Comment by capalmer85** [comment]
On Thu, Jun 2, 2016 at 3:29 PM, Krishna Thapa notifications@github.com
wrote:

> @capalmer85 https://github.com/capalmer85 lumiValidate.get_data and
> other methods have very specific requirement on argument. Calling those
> methods from makeBPerLumiNTs.py is going to be a challenge. One way around
> is to pipe out the data used for plots to a file and read it again.
> 'print merged, got_cols, fill ' at the end of get_data method should do
> the trick.
> 
> Yes, I see.  I just took a look at the code and the histograms are probably
> not so easily accessible.  I wonder if you can just make the brilcalc calls
> again from your script and then run the algorithms on the values in the
> CSVs (or a dictionary in local memory).

What do you think?

**Comment by plujan** [comment]
closing old issues (especially since this was superseded long ago by the fill validation)
